services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # amqp
      - "15672:15672" # management
